services:
  minio:
    image: bitnami/minio:2024.12.18
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minioadmin # Change this
      - MINIO_ROOT_PASSWORD=043ec277661d48bebab2972fd6043ebf # Change this
      - MINIO_DEFAULT_BUCKETS=distapp
    volumes:
      - 'minio_data:/bitnami/minio/data'
volumes:
  minio_data: